import type { Metadata } from "next";
import { Bitter, Work_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bitter = Bitter({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "100"],
  display: "swap",
  variable: "--font-bitter",
  subsets: ["cyrillic-ext", "cyrillic", "latin-ext", "latin", "vietnamese"],
});

const work_sans = Work_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "100"],
  display: "swap",
  variable: "--font-work-sans",
  subsets: ["latin", "latin-ext"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` min-w-full ${bitter.variable} ${work_sans.variable}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
